-- Convert the standard recycling recipes generated by the recycler mod for this mod's items so they only work in the chronocycler.
-- Custom recipies should use the crafting category pre.."reverse-chronocycling"

local recipeTempIcon = prismarisConstants.iconsPath .. "recipe-temp.png"

-- Simple mode
if settings.startup["test-reversal-mode"].value == "simple" then
	for name,recipe in pairs(data.raw.recipe) do
		if string.find(name,pre) and string.find(name,"-recycling") then -- if the recipe has the prismaris prefix and the recycling suffix
			recipe.categories = {pre.."reverse-chronocycling"} -- change the category.
			local mainItem = recipe.ingredients[1].name
			recipe.localised_name = {"recipe-name.reversal",pf.getLocalisedName(mainItem)}
			recipe.crafting_machine_tint = keys.tint(color.concentratedVoid).crafting_machine_tint
		end
	end
end

-- TODO:
-- * Script to add them to reversal technology.
-- * Script to generate reversal icons.

--[[
	Spoilage Inversion:
	1. Add reverse chronocycling category to all recycling recipes.
		(Enables default recycling in chronocycler)
	2. Remove default recycling category from all prismaris items.
		(Prohibit default recycling of prismaris items)
	3. Remove reverse chronocycling category from all post-spoil recycling.
		(Spoilage + prismaris perishables cannot be reverse chronocycled.)
	4. Completely erase default recycling recipes of post-spoil prismaris items.
		(Prismaris perishables can't be re/chronocycled at all; others can still be default recycled)
	5. Create custom spoilage-inversion recipes.
		(Spoilage -> Original Perishables)

	Spoilage inversion is probabilistic based on spoil time; the faster it originally spoils the less likely it is to emerge from the recipe.
	How to calculate:
	1. Loop through all items. Exclude any items that have the phrace "science-pack" in their name. Exclude items that spoil into entities, like biter eggs.
	2. If it can spoil, record in spoilage table:
		spoilMap[item.spoil_result] = {
			sources = {
				{item.name,item.spoil_ticks},
				...
			},
			total_spoil_ticks = #
		}
	3. for each spoilage result, loop through the possible sources and add up their spoil times.
	4. probability of getting a result:
		a. for each item, calculate total_spoil_ticks/item.spoil_ticks
		b. sum all results from a
		c. divide item.a / sum(a) to get specific normalized percentages.
		d. multiply final percentages by 0.8 to simulate 20% loss.

	For example, vanilla spoilage would become approximately:
		~ 32.01% yumako mash
		~ 24.01% jelly
		~ 19.21% nutrients
		~ 1.6% jellynut
		~ 1.6% yumako
		~ 0.8% bioflux
		~ 0.7% raw fish

]]

if settings.startup["test-reversal-mode"].value == "complex" then
	data.raw["furnace"][pre .. "reversal-chronocycler"].crafting_categories = {pre.."reverse-chronocycling"} -- Reduce chronocycler to just chronocycling recipes.

	for name,recipe in pairs(data.raw.recipe) do
		if string.find(name,"-recycling") then
			if string.find(name,pre) then
				recipe.categories = {pre.."reverse-chronocycling"} -- make prismaris recipes ONLY chronocycling by removing default recycling category (mostly intended for non-spoiling prismaris items)
				local mainItem = recipe.ingredients[1].name
				recipe.localised_name = {"recipe-name.reversal",pf.getLocalisedName(mainItem)}
			else
				table.insert(recipe.categories,pre.."reverse-chronocycling") -- Make all other recycling also chronocycling by adding chronocycling category
			end
		end
	end

	local spoilMap = {}

	data:extend{
		{
			type="recipe-category",
			name=pre.."uncraftable"
		}
	}

	for type_name in pairs(defines.prototypes.item) do
		if data.raw[type_name] then
			for name,item in pairs(data.raw[type_name]) do -- Look through all possible items
				if item.spoil_ticks ~= nil and item.spoil_ticks > 0 and item.spoil_result ~= nil and string.find(name, "science-pack",1,true) == nil and string.find(item.spoil_result, "science-pack",1,true) == nil then -- if item has spoilage AND is not a science pack
					spoilMap[item.spoil_result] = spoilMap[item.spoil_result] or {sources = {}, total_spoil_ticks = 0} -- initialize the map
					table.insert(spoilMap[item.spoil_result].sources, {name,item.spoil_ticks}) -- insert item into map
					spoilMap[item.spoil_result].total_spoil_ticks = spoilMap[item.spoil_result].total_spoil_ticks + item.spoil_ticks -- sum total_spoil_ticks
					
					
					local recipe = data.raw.recipe[item.spoil_result .. "-recycling"] or {}
					for key,value in pairs(recipe.categories or {}) do
						if value == pre .. "reverse-chronocycling" then
							data.raw.recipe[item.spoil_result .. "-recycling"].categories[key] = nil -- remove reverse chronocycling category from all post-spoil items to make way for custom recipes.
							local categoriesEmpty = true
							for i,k in pairs(data.raw.recipe[item.spoil_result .. "-recycling"].categories) do
								categoriesEmpty = false -- check if there are any crafting categories left on the recipe
							end
							if categoriesEmpty then
								recipe.categories = {pre.."uncraftable"} -- give a recipe a crafting category but leave it uncraftable
							end
						end
					end
					
				end
			end
		end
	end
	--log(serpent.block(spoilMap))

	for spoilItem,mapping in pairs(spoilMap) do
		local a_total = 0
		local results = {}
		for i,source in ipairs(spoilMap[spoilItem].sources) do 
			source.a = (spoilMap[spoilItem].total_spoil_ticks / source[2])
			a_total = a_total + source.a
		end
		local b_total = 0
		for i,source in ipairs(spoilMap[spoilItem].sources) do 
			source.b = (source.a / a_total)
			source.probability = {min = math.max(0,b_total), max = math.min(b_total + source.b,1)}
			b_total = b_total + source.b
			table.insert(results,{source[1],1,sp=source.probability})
		end
		local recipe = data.raw.recipe[spoilItem .. "-recycling"] or {}
		local energy = recipe.energy_required or 0.1
		data:extend({
			pf.recipeFactory(
				spoilItem .. "-reversal",
				recipeTempIcon,
				pf.itemIngredientsFactory({
					{spoilItem,1}
				}),
				pf.itemResultsFactory(results),
				energy,
				{pre.."reverse-chronocycling"},
				keyMerge(
					recipe.order,
					{
						keys.standard,
						keys.tint(color.concentratedVoid),
						{
							hidden=true,
							unlock_results=false,
							localised_name = {"recipe-name.reversal",pf.getLocalisedName(spoilItem)}
						}
					}
				)
			)
		})
		table.insert(data.raw.technology["chronocycler-reversal"].effects, {type = "unlock-recipe", recipe = spoilItem .. "-reversal"})
	end
	
end